
architecture_config:
  block1:
    layer1:
      input_channel : 3
      output_channel : 32
      kernel_size : 3
      padding : 1
      batchnorm : 32


    layer2:
      input_channel: 32
      output_channel: 32
      kernel_size: 3
      padding: 1
      batchnorm : 32
      max_pool : 2

  block2:
    layer1:
      input_channel : 32
      output_channel : 64
      kernel_size : 3
      padding : 1
      batchnorm : 64
      max_pool : 2

    layer2:
      input_channel: 64
      output_channel: 64
      kernel_size: 3
      padding: 1
      batchnorm : 64
      max_pool : 2

  block3:
    layer1:
      input_channel : 64
      output_channel : 128
      kernel_size : 3
      padding : 1
      batchnorm : 128
      max_pool : 2

    layer2:
      input_channel: 128
      output_channel: 128
      kernel_size: 3
      padding: 1
      batchnorm : 128
      max_pool : 2

  block4:
    layer1:
      input_channel : 128
      output_channel : 256
      kernel_size : 3
      padding : 1
      batchnorm : 256
      max_pool : 2
      adp_avg_pool : 7

  classifier:
    fc1_input : 256
    filter : 7
    fc1_output : 256
    fc1_dropout : 0.4

    fc2_input : 256
    fc2_output : 128
    fc2_dropout : 0.4

    fc3_input : 128
    fc3_output : 3 # The number of classes in the images datasets


